### ISSUE TITLE
push错误和AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by TimeJason** [arlettebrook/tencentVideoSign-in-Actions#1]
> File "/home/runner/work/autoCheck-in/autoCheck-in/tencentVideoSign-in-Actions/config.py", line 216, in tencent_video_get_score
    qq_nick = re.search(r"qq_nick=([^\n;]*);", auth_cookies).group(1)
看了一下大佬的源码，和自己的报错。
qq_nick = re.search(r"qq_nick=([^\n;]*);", auth_cookies).group(1)
这段代码运行的时候似乎出现了问题，我看了一下返回的log里面返回的是score_resp，但是我怀疑是auth_cookies里面的qq_nick键值找不到，不知道大佬有没有这个问题（ps我的名字好像就是空，所以我怀疑是这个问题）

以下是push log的错误，玩不太来git不太会修哈哈哈，大佬能指导一下吗，目测可能要把大佬代码copy到本地，不太懂
To https://github.com/TimeJason/autoCheck-in
 ! [rejected]        HEAD -> main (non-fast-forward)
error: failed to push some refs to 'https://github.com/TimeJason/autoCheck-in'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Invalid status code: 1

**Comment by arlettebrook** [comment]
> > File "/home/runner/work/autoCheck-in/autoCheck-in/tencentVideoSign-in-Actions/config.py", line 216, in tencent_video_get_score
> > qq_nick = re.search(r"qq_nick=([^\n;]_);", auth_cookies).group(1)
> > 看了一下大佬的源码，和自己的报错。
> > qq_nick = re.search(r"qq_nick=([^\n;]_);", auth_cookies).group(1)
> > 这段代码运行的时候似乎出现了问题，我看了一下返回的log里面返回的是score_resp，但是我怀疑是auth_cookies里面的qq_nick键值找不到，不知道大佬有没有这个问题（ps我的名字好像就是空，所以我怀疑是这个问题）
> 
> 以下是push log的错误，玩不太来git不太会修哈哈哈，大佬能指导一下吗，目测可能要把大佬代码copy到本地，不太懂 To https://github.com/TimeJason/autoCheck-in ! [rejected] HEAD -> main (non-fast-forward) error: failed to push some refs to 'https://github.com/TimeJason/autoCheck-in' hint: Updates were rejected because the tip of your current branch is behind hint: its remote counterpart. Integrate the remote changes (e.g. hint: 'git pull ...') before pushing again. hint: See the 'Note about fast-forwards' in 'git push --help' for details. Error: Invalid status code: 1

我也是小白，用户名获取是随机加上的，并且只能获取QQ账号的账户名。

目前已经修复账户名获取失败之后不会影响后面的代码运行，后面看有时间会重新写一下用户名获取的方法，如果你已经有好的解决办法欢迎提交

仓库报错，需要重新拉取仓库，出现冲突把不要的log日志删掉，重新提交就行
